---
title: "The GIS Job Market"
author: GEOG 40323
date: April 24, 2018
output: 
  revealjs::revealjs_presentation: 
    theme: "black"
    transition: "none"
    center: TRUE
    fig_caption: TRUE
    highlight: "zenburn"
    
---

## Upcoming dates

* Lab 8 due __Wednesday, May 2__
* Next week: project time; I'm available to print posters and for last-minute meetings
* May 7: I'm available to print posters and for extra-last-minute meetings
    * Final papers due at 11:59 pm
* May 8: Poster presentation session at 11:00 in Rees-Jones 211
    * Posters due May 8 - get them done early!

---

## Posters

* Templates available at http://cis.tcu.edu/default.asp?f=media-production&sf=graphics-production&p=research-posters
* For inspiration, check the examples in the Geography office
* Guest speaker: Dr. Ashley Coles

---

## Presentations

* To commence May 8 at 11:00am in Rees-Jones 211
* You will stand by your posters for 15 minutes; view your colleagues' presentations the rest of the time
* Five 15-minute sessions; break in the middle
* __YOU MUST ATTEND THE ENTIRE PRESENTATION SESSION TO RECEIVE CREDIT FOR YOUR POSTERS__

---

## Final reports

* Format for the final report: ~8 pages, double-spaced
* Sections: 
    * Introduction
    * Background / literature review
    * Research design, data, and methodolology
    * Results and deliverables
    * Conclusion and reflections

---

## The GIS job market

---

## GIS jobs

* The GIS jobs map: http://gisjobsmap.com/

---

### Urban & Business GIS jobs

Examples: 

* [GIS Research Analyst, JLL](https://jll.wd1.myworkdayjobs.com/en-US/jllcareers/job/Atlanta-GA/GIS-Research-Analyst_REQ3804?source=APPLICANT_SOURCE-6-41&codes=D_Indeed)
* [Real Estate Analyst, Panda Restaurant Group](https://pandarg.referrals.selectminds.com/jobs/real-estate-analyst-22845)
* [Consumer Analytics Lead (GIS), Harley Davidson](https://jobs.harley-davidson.com/job/Milwaukee-Consumer-Analytics-Lead-%28GIS%29-WI-53201/470024800/?feedId=4&utm_source=Indeed)

Tutorial: how to search for jobs on Indeed.com

---

## Is GIS a career?

* Operating GIS software and pushing buttons in ArcGIS **is not** a career
* However, the ability to **work with geospatial datasets** and **apply geographic analytical techniques** is in high demand!
* Emerging field you need to be aware of: _data science_

---

### How can you get your foot in the door? 

My advice: 

* Informational interviews
* Internships
* Independent training and self-study
* Marketing yourself (website, e-portfolio, LinkedIn)

---

## Informational interviews

* A sort of "reverse interview" in which you reach out to professionals to ask them about their experiences in the field
* **DO NOT** make it seem like you are looking for a job (even though you probably are)
* It is better to be known than unknown in a stack of resumes...

---

## Internships

* [Article from *The Chronicle* on "The Employment Mismatch"](https://chronicle.com/article/The-Employment-Mismatch/137625/#id=overview)
* Key quote: "However, it's fundamental abilities that he says recent graduates lack, like how to analyze large amounts of data or construct a cogent argument. **"It's not a matter of technical skill,"** he says, **"but of knowing how to think."** "

TALK TO TERRENCE HOOD AND THE CAREER CENTER!

---

### Independent training and self-study

* To be successful, your learning has to continue after you leave TCU
* Options: 
    * Online open courseware (e.g. from [Penn State's online MGIS program](http://open.ems.psu.edu/courseware))
    * MOOCs (e.g. [Coursera](https://www.coursera.org/))
    * DataCamp: http://www.datacamp.com 


---

### Marketing yourself

* Ask yourselves: if an employer were to Google me, what would they find?  
* Options: website, blog/e-portfolio, LinkedIn
* Good options: Wordpress, Weebly, Wix



<style>

.reveal section img {
  background:none; 
  border:none; 
  box-shadow:none;
  }
  
</style>

